apiVersion: apps/v1
kind: Deployment
metadata:
  name: golos-v1
  labels:
    app-label: golos-v1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app-label: golos-v1
  template:
    metadata:
      labels:
        app-label: golos-v1
    spec:
      containers:
      - name: golos-v1
        image: cr.yandex/crpsdee4cj9f5r7k87ic/golos:v1
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          - name: PORT
            value: "6432"
          - name: DATABASE_HOST
            value: "rc1a-7hralt7zq1xy378o.mdb.yandexcloud.net"
          - name: USER
            value: "golos"
          - name: PASSWORD
            value: "golosgolos"
          - name: SPRING_RABBITMQ_HOST
            value: rabbitmq-3management