CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;
COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';

CREATE USER test WITH ENCRYPTED PASSWORD 'test';

CREATE DATABASE golosbd OWNER test;
