server:
  port: 8080
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE} #spring.profiles.active#
  liquibase:
    enabled: true
#    drop-first: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: public
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rtkit_golos
    username: postgres
    password: Ronaldo2003
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
    template:
      receive-timeout: 30000
