server:
  port: 8080
spring:
  thymeleaf:
    prefix: classpath:/templates
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: public
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://rc1a-7hralt7zq1xy378o.mdb.yandexcloud.net:6432/golos
    username: golos
    password: golosgolos
  rabbitmq:
    host: 158.160.150.41
#    host: rabbitmq
    port: 5672
    username: admin
    password: admin
    template:
      receive-timeout: 30000
