server:
  port: 8080
spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: public
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6432/golosbd
    username: postgres
    password: padmin
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    template:
      receive-timeout: 30000
