server:
  port: 8080
spring:
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rtkit_golos
    username: test
    password: test
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    template:
      receive-timeout: 30000
