apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: rabbitmq-3management
  labels:
    app-label: rabbitmq-3management
spec:
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: plaintext
      port: 15672
      targetPort: 15672
  selector:
    app-label: rabbitmq-3management
  type: LoadBalancer