version: "3.4"
services:
  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - "RABBITMQ_DEFAULT_USER=admin"
      - "RABBITMQ_DEFAULT_PASS=admin"
    networks:
      backend: { aliases: [rabbitmq.backend] }

networks:
  backend:
    driver: bridge